// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using _0_Framework.Domain;
using System;
using System.Collections.Generic;

namespace Company.Domain.EvidenceDetail
{
    public class EvidenceDetail : EntityBase
    {
        public EvidenceDetail(DateTime? fromDate, DateTime? toDate, string title, string day, long evidence_Id, string description)
        {
            FromDate = fromDate;
            ToDate = toDate;
            Title = title;
            Day = day;
            Description = description;
            Evidence_Id = evidence_Id;
        }

        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public string Title { get; set; }
        public string Day { get; set; }
        public string Description { get; set; }
        public long Evidence_Id { get; set; }

        public Evidence.Evidence Evidence { get; set; }

        public void Edit(DateTime? fromDate, DateTime? toDate, string title, string day, long evidence_Id, string description)
        {
            FromDate = fromDate;
            ToDate = toDate;
            Title = title;
            Day = day;
            Description = description;
            Evidence_Id = evidence_Id;
        }
    }
}